"""Check public boundaries, locale conservation and actual exported routes."""
import argparse, collections, html.parser, json, pathlib, re, urllib.parse, xml.etree.ElementTree as ET
p=argparse.ArgumentParser();p.add_argument('--out',type=pathlib.Path,required=True);p.add_argument('--receipt',type=pathlib.Path);a=p.parse_args();root=a.out.resolve();here=pathlib.Path(__file__).resolve().parent
site=json.loads((here/'site.json').read_text());origin=site['origin'];media=json.loads((here/'content/media.json').read_text());languages=site['languages'];langcodes={x['code'] for x in languages};pages={};link_count=0;videos=[];titles=collections.defaultdict(list)
class Page(html.parser.HTMLParser):
 def __init__(self,path):
  super().__init__();self.path=path;self.canonical=None;self.robots=None;self.video=[];self.description=None;self.alternates={};self.lang=None;self.dir=None;self.analytics=None;self.personal_home=False
 def handle_starttag(self,tag,attrs):
  global link_count
  d=dict(attrs)
  if tag=='html':self.lang=d.get('lang');self.dir=d.get('dir')
  if tag=='meta' and d.get('name')=='description':self.description=d.get('content')
  if tag=='meta' and d.get('name')=='robots':self.robots=d.get('content')
  if tag=='link' and d.get('rel')=='canonical':self.canonical=d.get('href')
  if tag=='link' and d.get('rel')=='alternate':self.alternates[d['hreflang']]=d['href']
  if tag=='video':self.video.append(d)
  if tag=='script' and d.get('src')=='/assets/site.js':self.analytics=d.get('data-ga')
  if tag=='a' and d.get('href')==site['author']['home']:self.personal_home=True
  for key in ('href','src','poster'):
   val=d.get(key,'')
   if val.startswith('/'):
    f=root/urllib.parse.unquote(val.lstrip('/'));f=f/'index.html' if val.endswith('/') else f
    assert f.is_file(),(str(self.path),val);link_count+=1
for f in root.rglob('index.html'):
 text=f.read_text();check=Page(f);check.feed(text);url=origin+'/'+f.relative_to(root).as_posix().removesuffix('index.html')
 assert check.canonical==url,(f,check.canonical,url)
 assert check.description and check.robots and check.lang in langcodes
 assert check.dir==next(x['dir'] for x in languages if x['code']==check.lang)
 assert check.analytics==site['analytics']['measurement_id'] and check.personal_home
 assert not re.search(r'/Users/|file:///|finance-secrets|BEGIN PRIVATE KEY|Codex|Claude|GPT[- ]|AI.generated|generated by|director review pending',text,re.I),f
 if check.robots=='index,follow':
  assert set(check.alternates)==langcodes|{'x-default'},f
  title=re.search(r'<title>(.*?)</title>',text).group(1);titles[(check.lang,title)].append(url)
 pages[url]=check
 playlist=re.search(r'<script type="application/json" id="playlist">(.*?)</script>',text)
 if playlist:
  entries=json.loads(playlist.group(1));assert all(x['id'] in {m['id'] for m in media} for x in entries)
 for s in re.findall(r'<script type="application/ld\+json">(.*?)</script>',text):
  schema=json.loads(s)
  if schema.get('@type')=='VideoObject':
   assert len(check.video)==1 and check.video[0]['src']==schema['contentUrl']
   assert all(schema.get(k) for k in ('name','description','thumbnailUrl','uploadDate','contentUrl','duration'))
   assert schema['inLanguage']==next(m['original_language'] for m in media if m['links']['main']==schema['contentUrl']) and schema['thumbnailUrl'][0]==origin+check.video[0]['poster']
   assert check.video[0]['preload']=='none'
   if check.robots=='index,follow':videos.append(url)
for url,c in pages.items():
 for lang,target in c.alternates.items():
  assert target in pages,(url,target)
  other=pages[target]
  assert other.alternates.get(c.lang)==url,(url,target)
  if lang!='x-default':assert other.lang==lang
assert all(len(v)==1 for v in titles.values()),{k:v for k,v in titles.items() if len(v)>1}
ns={'s':'http://www.sitemaps.org/schemas/sitemap/0.9','v':'http://www.google.com/schemas/sitemap-video/1.1'}
urls=[x.text for x in ET.parse(root/'sitemap.xml').findall('.//s:loc',ns)];vurls=[x.text for x in ET.parse(root/'video-sitemap.xml').findall('.//s:loc',ns)]
assert set(urls)=={u for u,c in pages.items() if c.robots=='index,follow'} and len(urls)==len(set(urls))
assert set(vurls)==set(videos) and len(vurls)==len(set(vurls))
assert len(videos)==sum(m['index'] for m in media)*len(languages)
assert len(media)==len({m['id'] for m in media})
base_ui=json.loads((here/'locales/en.json').read_text())['ui'];ct=here/'content/cases/bitcoin-solo-miner/locales';base_case=json.loads((ct/'en.json').read_text())
for lang in languages:
 d=json.loads((here/'locales'/f'{lang["code"]}.json').read_text());assert d['ui'].keys()==base_ui.keys()
 c=json.loads((ct/f'{lang["code"]}.json').read_text());assert c.keys()==base_case.keys()
 for k in c:assert c[k].keys()==base_case[k].keys(),(lang['code'],k)
 if lang['code']!='en':assert c['case']['summary']!=base_case['case']['summary'] and c['case']['role']!=base_case['case']['role']
 for m in media:assert c['topics'][m['topic']]
assert 'Disallow: /\n' not in (root/'robots.txt').read_text()
for line in (root/'_redirects').read_text().splitlines():assert line.startswith('/') and ' 301' in line
receipt={'pass':True,'languages':len(languages),'unique_videos':len(media),'html_pages':len(pages),'indexable_pages':len(urls),'indexable_watch_pages':len(videos),'internal_links_checked':link_count,'reciprocal_hreflang':True,'self_canonicals':True,'original_video_language':True,'unique_indexable_titles':True,'all_locale_keys_present':True,'shared_analytics_and_personal_home':True,'public_boundary':True}
if a.receipt:a.receipt.parent.mkdir(parents=True,exist_ok=True);a.receipt.write_text(json.dumps(receipt,indent=2)+'\n')
print(json.dumps(receipt))
